table 'Claimants Pending EDD Action'
	lineageTag: 5e2d14d7-7173-4a14-9fc1-2790ae0fed26

	column 'CALIFORNIA UNEMPLOYMENT INSURANCE (UI) Claims DATA DASHBOARD '
		dataType: string
		lineageTag: 767b982c-22e0-485e-a551-b3eea67fe74d
		summarizeBy: none
		sourceColumn: "CALIFORNIA UNEMPLOYMENT INSURANCE (UI) Claims DATA DASHBOARD "

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 3934e738-d699-4ad4-a5c8-12ceb318e628
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: b7de020e-d5a6-4f06-bcc1-a40d5722aac0
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: b71d03df-3341-49c3-b560-1fab1758673c
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: d589163e-5435-4759-89cb-c87137897492
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 77a6c836-fd62-4c42-9cbf-f8f1f3c29d9f
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: d3c10abe-6542-4442-9265-2a5d7c9bd145
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: e194882b-33fa-4f9a-9654-77a258aa32aa
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 5004342e-7e96-4dbb-bca5-6acdeb2bdc48
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: bb58415a-9643-4562-8c86-2a853ffa82bc
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: fe06e2bc-43eb-4413-942b-b91977d9f673
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 38fc1c0c-92cc-428c-9169-34e450bae345
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 34409d5e-6257-467e-9418-7a785ff0f02a
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	partition 'Claimants Pending EDD Action' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Michael\unemployment-insurance-claims-data.xlsx"), null, true),
				    #"Claimants Pending EDD Action_Sheet" = Source{[Item="Claimants Pending EDD Action",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Claimants Pending EDD Action_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CALIFORNIA UNEMPLOYMENT INSURANCE (UI) Claims DATA DASHBOARD ", type any}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

